"""
generate_paper_figures.py — Generate publication-quality figures for paper (v8+)
Canonical location: scripts/07_figures/generate_paper_figures.py
Figures 2-5 generated from parquet data and report CSVs.
Figure 1 is generated by scripts/09_regime_timeline_figure.py.
"""
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import warnings
warnings.filterwarnings('ignore')

from pathlib import Path
PAPER = Path(__file__).resolve().parent.parent.parent  # repo root
OUT   = str(PAPER / 'paper' / 'figures')
PAPER = str(PAPER)

# ─── Style ────────────────────────────────────────────────────────────────────
plt.rcParams.update({
    'font.family':      'serif',
    'font.serif':       ['Times New Roman', 'DejaVu Serif'],
    'font.size':        11,
    'axes.titlesize':   12,
    'axes.labelsize':   11,
    'legend.fontsize':  9.5,
    'xtick.labelsize':  10,
    'ytick.labelsize':  10,
    'axes.spines.top':  False,
    'axes.spines.right':False,
    'figure.dpi':       300,
    'savefig.dpi':      300,
    'savefig.bbox':     'tight',
    'savefig.facecolor':'white',
    'axes.facecolor':   'white',
    'figure.facecolor': 'white',
    'grid.alpha':        0.3,
    'grid.linestyle':   '--',
    'grid.linewidth':   0.5,
})

# Colorblind-friendly palette (Okabe-Ito)
COLORS = {
    'equal_weight_risky': '#CC79A7',  # pink/mauve
    'stoxx600':           '#999999',  # grey
    'static_cvar':        '#0072B2',  # blue (bold)
    'markowitz':          '#56B4E9',  # sky blue
    'regime_cvar_A':      '#E69F00',  # orange
    'weighted_cvar':      '#D55E00',  # vermilion
}
LABELS = {
    'equal_weight_risky': 'Equal-Weight (1/N)',
    'stoxx600':           'STOXX Europe 600',
    'static_cvar':        'Static CVaR',
    'markowitz':          'Markowitz (Min-Var)',
    'regime_cvar_A':      'Regime CVaR-A',
    'weighted_cvar':      'Weighted CVaR',
}
LINESTYLES = {
    'equal_weight_risky': '--',
    'stoxx600':           ':',
    'static_cvar':        '-',
    'markowitz':          '-.',
    'regime_cvar_A':      (0, (3,1,1,1)),
    'weighted_cvar':      (0, (5,2)),
}

# ─────────────────────────────────────────────────────────────────────────────
# FIGURE 2 — Cumulative Wealth, Panel B
# ─────────────────────────────────────────────────────────────────────────────
def fig2():
    df = pd.read_parquet(f'{PAPER}/data/processed/panel_b_returns.parquet')
    df = df.dropna(how='all')

    # Compute cumulative wealth from first common date
    cols = ['equal_weight_risky','stoxx600','static_cvar','markowitz','regime_cvar_A','weighted_cvar']
    first_full = df[cols].dropna().index[0]
    sub = df.loc[first_full:, cols].fillna(0)
    wealth = (1 + sub).cumprod()

    fig, ax = plt.subplots(figsize=(8.5, 4.2))

    for col in cols:
        lw = 2.0 if col == 'static_cvar' else 1.4
        ax.plot(wealth.index, wealth[col],
                color=COLORS[col], lw=lw,
                linestyle=LINESTYLES[col],
                label=LABELS[col], zorder=3)

    # Crisis bands
    crisis_bands = [
        ('2011-07-01', '2012-09-30', 'Eurozone\nCrisis'),
        ('2020-01-01', '2020-06-30', 'COVID-19'),
        ('2022-01-01', '2022-12-31', '2022 Rate\nShock'),
    ]
    for start, end, label in crisis_bands:
        ax.axvspan(pd.Timestamp(start), pd.Timestamp(end),
                   color='#AAAAAA', alpha=0.18, zorder=1)
        mid = pd.Timestamp(start) + (pd.Timestamp(end) - pd.Timestamp(start)) / 2
        ax.text(mid, ax.get_ylim()[1] if ax.get_ylim()[1] > 1.5 else 1.7,
                label, ha='center', va='top', fontsize=8, color='#555555', style='italic')

    ax.axhline(1, color='black', lw=0.7, ls='-', zorder=2)
    ax.set_xlabel('Date')
    ax.set_ylabel('Cumulative Wealth ($1 initial)')
    # No embedded figure title - Word caption controls numbering
    ax.legend(loc='upper left', ncol=2, frameon=True, framealpha=0.92,
              edgecolor='#CCCCCC', borderpad=0.5)
    ax.grid(True, axis='y')
    ax.xaxis.set_major_formatter(matplotlib.dates.DateFormatter('%Y'))
    plt.tight_layout()
    out = f'{OUT}/figure_2_cumulative_wealth_panel_b.png'
    plt.savefig(out)
    plt.close()
    print(f'Saved: {out}')

# ─────────────────────────────────────────────────────────────────────────────
# FIGURE 3 — Turnover vs Net Sharpe scatter
# ─────────────────────────────────────────────────────────────────────────────
def fig3():
    # Build data points from various CSVs
    # [label, annual_TO%, net_sharpe@10bps, marker, color, marker_size, zorder, exploratory]
    points = [
        # From panel_b_regime_oos_tc_sensitivity.csv
        ('Equal-Weight (1/N)',          35.2,  0.406, 'o', '#CC79A7', 60, 3, False),
        ('STOXX Europe 600',             0.0,  0.363, 's', '#999999', 60, 3, False),
        ('Static CVaR',                 21.4,  0.528, 'D', '#0072B2', 80, 5, False),
        ('Markowitz (Min-Var)',          12.3,  0.445, '^', '#56B4E9', 60, 3, False),
        ('Regime CVaR-A',              225.8,  0.346, 'o', '#E69F00', 60, 3, False),
        ('Weighted CVaR',              232.5,  0.348, 'o', '#D55E00', 60, 3, False),
        # From tc_aware performance (tau=0.10, 10bps)
        ('CVaR-A, τ=0.10',             59.9,  0.486, 'v', '#E69F00', 60, 4, False),
        ('Weighted CVaR, τ=0.10',      61.5,  0.486, 'v', '#D55E00', 60, 4, False),
        # From regime_constraints (10 bps) — corrected State 2/3 mapping 2026-05-12
        ('RC-CVaR (baseline)',          29.2,  0.519, 'P', '#009E73', 70, 4, False),
        ('RC-CVaR (ZEW-swap)',          27.0,  0.517, 'P', '#007050', 70, 4, False),
        # Exploratory ZEW + lambda
        ('ZEW+λ=0.005 (exploratory)',  64.8,  0.567, '*', '#888888', 90, 4, True),
    ]

    fig, ax = plt.subplots(figsize=(7.5, 4.5))

    for label, to, sharpe, marker, color, ms, zo, exploratory in points:
        if exploratory:
            ax.scatter(to, sharpe, marker=marker, color=color, s=ms, zorder=zo,
                       edgecolors='#555555', linewidths=0.8, alpha=0.75)
        else:
            ax.scatter(to, sharpe, marker=marker, color=color, s=ms, zorder=zo,
                       edgecolors='white', linewidths=0.6)

        # Offsets for label placement
        offsets = {
            'Static CVaR':               (-3,  6),
            'Equal-Weight (1/N)':        (4,  -10),
            'STOXX Europe 600':          (4,  5),
            'Markowitz (Min-Var)':       (4, -10),
            'Regime CVaR-A':             (4,   5),
            'Weighted CVaR':             (4, -10),
            'CVaR-A, τ=0.10':            (4,   5),
            'Weighted CVaR, τ=0.10':     (4, -10),
            'RC-CVaR (baseline)':        (-3, 6),
            'RC-CVaR (ZEW-swap)':        (4, -10),
            'ZEW+λ=0.005 (exploratory)': (4,  5),
        }
        dx, dy = offsets.get(label, (4, 4))
        fs = 8 if not exploratory else 7.5
        style = 'italic' if exploratory else 'normal'
        ax.annotate(label, (to, sharpe), xytext=(dx, dy),
                    textcoords='offset points', fontsize=fs, style=style,
                    color='#333333', va='center')

    # Highlight Static CVaR
    static_x, static_y = 21.4, 0.528
    ax.axhline(static_y, color='#0072B2', lw=0.8, ls='--', alpha=0.5, zorder=1)
    ax.text(240, static_y + 0.005, 'Static CVaR\nbenchmark', color='#0072B2',
            fontsize=8, va='bottom', ha='right')

    ax.set_xlabel('Annualized One-Way Turnover (%)')
    ax.set_ylabel('Net Sharpe Ratio (10 bps TC)')
    # No embedded figure title - Word caption controls numbering
    ax.set_xlim(-10, 260)
    ax.set_ylim(0.28, 0.61)
    ax.grid(True, alpha=0.3)
    plt.tight_layout()
    out = f'{OUT}/figure_3_turnover_vs_net_sharpe.png'
    plt.savefig(out)
    plt.close()
    print(f'Saved: {out}')

# ─────────────────────────────────────────────────────────────────────────────
# FIGURE 4 — Average weights: baseline vs FI-expanded Static CVaR
# ─────────────────────────────────────────────────────────────────────────────
def fig4():
    # From fi_expanded_comparison.md Section C — verified average weights over Panel B
    groups = ['European\nEquities', 'Real\nEstate', 'Gold', 'Bloomberg\nCommodity', 'Brent', 'Govt\nBonds']
    baseline_w  = [39.3,  9.7, 25.0, 25.0, 1.1,  0.0]  # from fi_expanded report
    fi_exp_w    = [ 3.0,  0.0, 10.0, 13.5, 0.0, 73.5]  # from fi_expanded report

    x = np.arange(len(groups))
    width = 0.35

    fig, ax = plt.subplots(figsize=(7.5, 4.0))

    bars1 = ax.bar(x - width/2, baseline_w, width, label='Baseline (11 assets)',
                   color='#0072B2', alpha=0.85, edgecolor='white', linewidth=0.5)
    bars2 = ax.bar(x + width/2, fi_exp_w,   width, label='FI-Expanded (14 assets)',
                   color='#E69F00', alpha=0.85, edgecolor='white', linewidth=0.5)

    # Value labels on bars > 1%
    for bar in bars1:
        h = bar.get_height()
        if h > 1:
            ax.text(bar.get_x() + bar.get_width()/2, h + 0.5, f'{h:.0f}%',
                    ha='center', va='bottom', fontsize=8, color='#222222')
    for bar in bars2:
        h = bar.get_height()
        if h > 1:
            ax.text(bar.get_x() + bar.get_width()/2, h + 0.5, f'{h:.0f}%',
                    ha='center', va='bottom', fontsize=8, color='#222222')

    ax.set_xticks(x)
    ax.set_xticklabels(groups)
    ax.set_ylabel('Average Weight (%)')
    # No embedded figure title - Word caption controls numbering
    ax.legend(frameon=True, framealpha=0.92, edgecolor='#CCCCCC')
    ax.set_ylim(0, 82)
    ax.grid(True, axis='y', alpha=0.3)
    ax.text(0.98, 0.97, 'Source: fi_expanded_comparison.md (reported averages)',
            transform=ax.transAxes, fontsize=7, ha='right', va='top',
            color='#888888', style='italic')
    plt.tight_layout()
    out = f'{OUT}/figure_4_static_cvar_weights_baseline_vs_fi.png'
    plt.savefig(out)
    plt.close()
    print(f'Saved: {out}')

# ─────────────────────────────────────────────────────────────────────────────
# FIGURE 5 — Drawdown: Baseline vs FI-Expanded Static CVaR
# ─────────────────────────────────────────────────────────────────────────────
def fig5():
    base_ret = pd.read_parquet(f'{PAPER}/data/processed/panel_b_returns.parquet')['static_cvar'].dropna()
    fi_ret   = pd.read_parquet(f'{PAPER}/data/processed/panel_b_returns_fi_expanded.parquet')['static_cvar'].dropna()

    def drawdown_series(returns):
        wealth = (1 + returns).cumprod()
        peak = wealth.cummax()
        return (wealth - peak) / peak * 100  # in percent

    dd_base = drawdown_series(base_ret)
    dd_fi   = drawdown_series(fi_ret)

    # Align
    idx = dd_base.index.intersection(dd_fi.index)
    dd_base = dd_base.loc[idx]
    dd_fi   = dd_fi.loc[idx]

    fig, ax = plt.subplots(figsize=(8.5, 4.0))

    ax.fill_between(dd_base.index, dd_base, 0, alpha=0.18, color='#0072B2', zorder=1)
    ax.fill_between(dd_fi.index,   dd_fi,   0, alpha=0.18, color='#E69F00', zorder=1)
    ax.plot(dd_base.index, dd_base, color='#0072B2', lw=1.8, label='Static CVaR (Baseline)', zorder=3)
    ax.plot(dd_fi.index,   dd_fi,   color='#E69F00', lw=1.8, ls='--', label='Static CVaR (FI-Expanded)', zorder=3)

    # 2022 rate-shock band
    ax.axvspan(pd.Timestamp('2022-01-01'), pd.Timestamp('2022-12-31'),
               color='#DD0000', alpha=0.07, zorder=2)
    ax.text(pd.Timestamp('2022-06-30'), -16, '2022\nRate Shock',
            ha='center', va='top', fontsize=8.5, color='#DD0000', style='italic')

    # COVID band
    ax.axvspan(pd.Timestamp('2020-01-01'), pd.Timestamp('2020-06-30'),
               color='#AAAAAA', alpha=0.15, zorder=2)
    ax.text(pd.Timestamp('2020-03-31'), -16, 'COVID-19',
            ha='center', va='top', fontsize=8, color='#555555', style='italic')

    ax.axhline(0, color='black', lw=0.7)
    ax.set_xlabel('Date')
    ax.set_ylabel('Drawdown (%)')
    # No embedded figure title - Word caption controls numbering
    ax.legend(frameon=True, framealpha=0.92, edgecolor='#CCCCCC')
    ax.grid(True, axis='y', alpha=0.3)
    ax.xaxis.set_major_formatter(matplotlib.dates.DateFormatter('%Y'))
    plt.tight_layout()
    out = f'{OUT}/figure_5_drawdown_baseline_vs_fi.png'
    plt.savefig(out)
    plt.close()
    print(f'Saved: {out}')

# ─────────────────────────────────────────────────────────────────────────────
# APPENDIX F — Descriptive Statistics
# ─────────────────────────────────────────────────────────────────────────────
def descriptive_stats():
    from scipy import stats as sp_stats
    ret = pd.read_parquet(f'{PAPER}/data/processed/investable_returns_weekly.parquet')
    # Use risky assets only (exclude EURIBOR)
    risky_cols = ['Bloomberg_Commodity','Brent','Gold','CAC_40','DAX',
                  'EuroStoxx50','FTSE_MIB','IBEX35','StoxxEurope600','FTSE_EPRA_NAREIT_Europe']
    ret = ret[risky_cols].dropna(how='all')

    short_names = {
        'Bloomberg_Commodity':       'Bloomberg Comm.',
        'Brent':                     'Brent',
        'Gold':                      'Gold',
        'CAC_40':                    'CAC 40',
        'DAX':                       'DAX',
        'EuroStoxx50':               'EuroStoxx 50',
        'FTSE_MIB':                  'FTSE MIB',
        'IBEX35':                    'IBEX 35',
        'StoxxEurope600':            'STOXX 600',
        'FTSE_EPRA_NAREIT_Europe':   'EPRA Europe',
    }

    rows = []
    for col in risky_cols:
        s = ret[col].dropna()
        mean_ann  = s.mean() * 52 * 100
        vol_ann   = s.std() * np.sqrt(52) * 100
        skew      = sp_stats.skew(s)
        kurt      = sp_stats.kurtosis(s, fisher=False)  # excess=False → normal=3
        wealth    = (1 + s).cumprod()
        peak      = wealth.cummax()
        dd        = (wealth - peak) / peak
        max_dd    = dd.min() * 100
        start     = s.index.min().strftime('%Y-%m')
        end       = s.index.max().strftime('%Y-%m')
        rows.append({
            'Asset': short_names[col],
            'Mean%': f'{mean_ann:.2f}',
            'Vol%':  f'{vol_ann:.2f}',
            'Skew':  f'{skew:.2f}',
            'Kurt':  f'{kurt:.2f}',
            'MaxDD%':f'{max_dd:.1f}',
            'Start': start,
            'End':   end,
        })

    df_stat = pd.DataFrame(rows)
    # Save as CSV for reference
    csv_out = f'{PAPER}/paper/tables/appendix_f_descriptive_stats.csv'
    df_stat.to_csv(csv_out, index=False)
    print(f'Saved descriptive stats: {csv_out}')

    # Pairwise correlations (weekly returns, full sample, risky assets)
    corr = ret[risky_cols].corr()
    short_list = [short_names[c] for c in risky_cols]
    corr.index = short_list
    corr.columns = short_list
    corr_out = f'{PAPER}/paper/tables/appendix_f_correlations.csv'
    corr.round(2).to_csv(corr_out)
    print(f'Saved correlations: {corr_out}')

    return df_stat, corr

if __name__ == '__main__':
    print('Generating Figure 2...')
    fig2()
    print('Generating Figure 3...')
    fig3()
    print('Generating Figure 4...')
    fig4()
    print('Generating Figure 5...')
    fig5()
    print('Computing descriptive stats...')
    df_stat, corr = descriptive_stats()
    print('\nDescriptive stats preview:')
    print(df_stat.to_string(index=False))
    p